name: Publish

runs:
  using: "composite"
  steps:

  - name: Download Package Artifacts
    uses: actions/download-artifact@v3
    with:
      name: Packages
      path: packages

  - name: TEST Display structure of downloaded files
    run: ls -R
    working-directory: packages

  - name: Create GitHub Release
    if: runner.os == 'Unknown'
    shell: bash
    run: |
      VERSION=$(grep "VERSION =" gudpy.spec | sed "s/.*\"\(.*\)\"/\1/g")
      git clone https://github.com/disorderedmaterials/scripts.git
      ./scripts/update-release -r disorderedmaterials/gudpy -t ${VERSION} -n "${VERSION}" -f ReleaseNotes.md packages/*

  - bash: |
      VERSION=$(grep "VERSION =" gudpy.spec | sed "s/.*\"\(.*\)\"/\1/g") 
      singularity remote login --username ${HARBOR_USER} --password ${HARBOR_SECRET} docker://harbor.stfc.ac.uk
      singularity push dist/GudPy-$VERSION.sif oras://harbor.stfc.ac.uk/isis_disordered_materials/gudpy:latest
    condition: and(eq(variables.osName, 'linux'), eq(variables.publishImage, 'true'))
    env:
        HARBOR_USER: $(HARBOR_USER)
        HARBOR_SECRET: $(HARBOR_SECRET)
    displayName: "Publish singularity image to Harbor registry."

