name: Publish

inputs:
  isRelease:
    type: boolean
    default: false

runs:
  using: "composite"
  steps:

  - name: Install singularity
    uses: eWaterCycle/setup-singularity@v7
    with:
      singularity-version: 3.8.3

  - name: Download Artifacts
    uses: actions/download-artifact@v3
    with:
      name: Packages
      path: ${{ github.workspace }}/packages

  - name: Download Prerequisites
    shell: bash
    run: |
      wget https://raw.githubusercontent.com/disorderedmaterials/scripts/master/update-release
      chmod u+x ./update-release

  - name: Set Information (Release)
    if: inputs.isRelease == true
    shell: bash
    run: |
      echo "gitHubReleaseTag=${{ env.gudPyVersion }}" >> ${GITHUB_ENV}
      echo "gitHubReleaseName=${{ env.gudPyVersion }}" >> ${GITHUB_ENV}
      echo "harborReleaseTag=latest" >> ${GITHUB_ENV}

  - name: Set Information (Continuous)
    if: inputs.isRelease == false
    shell: bash
    run: |
      echo "gitHubReleaseTag=continuous" >> ${GITHUB_ENV}
      echo "gitHubReleaseName='Continuous (${{ env.gudPyVersion }})'" >> ${GITHUB_ENV}
      echo "harborReleaseTag=continuous" >> ${GITHUB_ENV}

  - name: Publish on GitHub
    shell: bash
    run: |
      echo "Release tag will be: ${{ env.gitHubReleaseTag }}"
      echo "Release name will be: ${{ env.gitHubReleaseName }}"
      export GITHUB_TOKEN=${{ github.token }}
      ./update-release -r disorderedmaterials/gudpy -t ${{ env.gitHubReleaseTag }} -n "${{ env.gitHubReleaseName }}" -f ReleaseNotes.md packages/*

  - name: Publish on Harbor
    shell: bash
    run: |
      echo "Release tag will be: ${{ env.harborReleaseTag }}"
      singularity remote login --username ${HARBOR_USER} --password ${HARBOR_SECRET} docker://harbor.stfc.ac.uk
      ${SINGULARITY_ROOT}/bin/singularity push packages/GudPy-${{ env.gudPyVersion }}.sif oras://harbor.stfc.ac.uk/isis_disordered_materials/gudpy:${{ env.harborReleaseTag }}
