name: Package

runs:
  using: "composite"
  steps:

  - name: Install singularity
    uses: eWaterCycle/setup-singularity@v7
    with:
      singularity-version: 3.8.3

  - name: Create DMG (OSX)
    if: runner.os == 'MacOS'
    shell: bash
    run: |
      pip install dmgbuild
      sed -i "s/GudPy-.*.app/${{ env.gudPyVersion }}/g" ci/settings.py
      dmgbuild -s ci/settings.py "GudPy-${{ env.gudPyVersion }}" dist/GudPy-${{ env.gudPyVersion }}.dmg

  - name: Upload Artifacts (OSX)
    if: runner.os == 'MacOS'
    uses: actions/upload-artifact@v3
    with:
      name: Packages
      path: |
        dist/GudPy-*.dmg
        dist/GudPy-*-OSX

  - name: Create Zip (Windows)
    if: runner.os == 'Windows'
    shell: bash
    run: |
      7z a dist/GudPy-${{ env.gudPyVersion }}-Windows.zip dist/GudPy-${{ env.gudPyVersion }}/

  - name: Upload Artifacts (Windows)
    if: runner.os == 'Windows'
    uses: actions/upload-artifact@v3
    with:
      name: Packages
      path: |
        dist/GudPy-*-Windows.zip
        dist/GudPy-*-Windows.exe

  - name: Create Singularity Image (Linux)
    if: runner.os == 'Linux'
    shell: bash
    run: |
      sudo ${SINGULARITY_ROOT}/bin/singularity build dist/GudPy-${{ env.gudPyVersion }}.sif ci/singularity/ubuntu20.04.def

  - name: Upload Artifacts (Linux)
    if: runner.os == 'Linux'
    uses: actions/upload-artifact@v3
    with:
      name: Packages
      path: |
        dist/GudPy-*.sif
        dist/GudPy-*-Linux
