name: Package

runs:
  using: "composite"
  steps:

  - name: Install singularity
    uses: eWaterCycle/setup-singularity@v7
    with:
      singularity-version: 3.8.3

  - name: Create DMG (OSX)
    if: runner.os == 'MacOS'
    shell: bash
    run: |
      pip install dmgbuild
      VERSION=$(grep "VERSION =" gudpy.spec | sed "s/.*\"\(.*\)\"/\1/g")
      sed -i '' -e 's/VERSION/$VERSION/g' ci/settings.py
      dmgbuild -s ci/settings.py "GudPy-$VERSION" dist/GudPy-$VERSION.dmg

  - name: Upload Artifacts (OSX)
    if: runner.os == 'MacOS'
    uses: actions/upload-artifact@v3
    with:
      name: Packages
      path: |
        dist/GudPy-*.dmg
        dist/GudPy-*-OSX

  - name: Create Zip (Windows)
    if: runner.os == 'Windows'
    shell: bash
    run: |
      VERSION=$(grep "VERSION =" gudpy.spec | sed "s/.*\"\(.*\)\"/\1/g")
      7z a dist/GudPy-$VERSION-Windows.zip dist/GudPy-$VERSION/

  - name: Upload Artifacts (Windows)
    if: runner.os == 'Windows'
    uses: actions/upload-artifact@v3
    with:
      name: Packages
      path: |
        dist/GudPy-*-Windows.zip
        dist/GudPy-*-Windows.exe

  - name: Create Singularity Image (Linux)
    if: runner.os == 'Linux'
    shell: bash
    run: |
      VERSION=$(grep "VERSION =" gudpy.spec | sed "s/.*\"\(.*\)\"/\1/g")
      sudo ${SINGULARITY_ROOT}/bin/singularity build dist/GudPy-$VERSION.sif ci/singularity/ubuntu20.04.def

  - name: Upload Artifacts (Linux)
    if: runner.os == 'Linux'
    uses: actions/upload-artifact@v3
    with:
      name: Packages
      path: |
        dist/GudPy-*.sif
        dist/GudPy-*-Linux
