name: Get Code Version

runs:
  using: "composite"
  steps:

  - name: Grep Version
    shell: bash
    run: |
      set -ex
      GUDPY_VERSION=$(grep "VERSION =" gudpy.spec | sed "s/.*\"\(.*\)\"/\1/g")
      echo "GudPy code version is ${GUDPY_VERSION}"
      echo "gudPyVersion=${GUDPY_VERSION}" >> ${GITHUB_ENV}