parameters:
- name: 'version'
  default: '3.6'
  type: string
- name: 'arch'
  default: 'x64'
  type: string
- name: os
  default: 'ubuntu'
  type: string
- name: osName
  default: 'linux'
  type: string
- name: tag
  default: ''
  type: string
steps:
  - task: UsePythonVersion@0
    displayName: "Use Python Version ${{ parameters.version }}"
    inputs:
      versionSpec: ${{ parameters.version }}
      architecture: ${{ parameters.arch }}

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: "Install dependencies"
  
  - bash: |
      wget https://github.com/disorderedmaterials/Gudrun/releases/download/${{ parameters.tag }}/binaries-${{ parameters.tag }}-${{ parameters.osName }}.zip
      unzip binaries-${{ parameters. tag}}-${{ parameters.osName }}.zip
      mv binaries-${{ parameters. tag}}-${{ parameters.osName }} bin

  - script: |
      pip install pyinstaller
      pyinstaller gudpy.spec