parameters:
- name: 'version'
  default: '3.6'
  type: string
- name: 'arch'
  default: 'x64'
  type: string
- name: os
  default: 'ubuntu'
  type: string
- name: osName
  default: 'linux'
  type: string
- name: gudrunTag
  default: ''
  type: string
steps:
  - task: UsePythonVersion@0
    displayName: "Use Python Version ${{ parameters.version }}"
    inputs:
      versionSpec: ${{ parameters.version }}
      architecture: ${{ parameters.arch }}

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: "Install dependencies"
  
  - bash: |
      curl -L https://github.com/disorderedmaterials/Gudrun/releases/download/${{ parameters.gudrunTag }}/binaries-${{ parameters.gudrunTag }}-${{ parameters.osName }}.zip > binaries.zip
      unzip binaries.zip
      mv binaries-${{ parameters.gudrunTag }}-${{ parameters.osName }} bin
      curl -L https://github.com/disorderedmaterials/Gudrun/releases/download/${{ parameters.gudrunTag }}/startupFiles-${{ parameters.gudrunTag }}.zip > startupFiles.zip
      unzip startupFiles.zip
      mv StartupFiles bin
      
  - script: |
      pip install pyinstaller
      
  - bash: |
      if [[ "${{ parameters.osName }}" == "osx" ]]; then
          echo "Increasing timeouts on OSX."
          PYINSTALLER_PATH=$(pip show pyinstaller | grep Location)
          PYINSTALLER_PATH=$(echo "${PYINSTALLER_PATH}" | awk '{print $2}')
          PYINSTALLER_PATH="${PYINSTALLER_PATH}/pyinstaller/compat.py"
          sed -i '' -e 's/out, err = proc.communicate(timeout=60)/out, err = proc.communicate(timeout=240)/g' "${PYINSTALLER_PATH}"
          curl -fsSL -o install.sh https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
          brew install npm
          npm install -g create-dmg
      fi
  - bash: |
      pyinstaller gudpy.spec
      if [[ "${{ parameters.osName }}" == "osx" ]]; then
          create-dmg dist/*.app
          [ $? -eq 2 ]  || exit 0
      fi
  - bash: |
      if [[ "${{ parameters.osName }}" == "windows" ]]; then
          echo "Zipping unpacked version of GudPy, for Windows."
          VERSION=$(grep "VERSION =" gudpy.spec | sed "s/.*\"\(.*\)\"/\1/g")
          7z a dist/GudPy-$VERSION-windows.zip dist/GudPy-$VERSION/
      fi