steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      specificBuildWithTriggering: true
      downloadType: 'single'
      artifactName: 'linux-artifacts'
    displayName: 'Download Linux Artifacts'
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      specificBuildWithTriggering: true
      downloadType: 'single'
      artifactName: 'osx-artifacts'
    displayName: 'Download OSX Artifacts'
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      specificBuildWithTriggering: true
      downloadType: 'single'
      artifactName: 'windows-artifacts'
    displayName: 'Download Windows Artifacts'
  - bash: |
      VERSION=$(grep "VERSION =" gudpy.spec | sed "s/.*\"\(.*\)\"/\1/g")
      git clone https://github.com/disorderedmaterials/scripts.git
      ./scripts/update-release -r disorderedmaterials/gudpy -t ${VERSION} -n "${VERSION}" -f ReleaseNotes.md $(System.ArtifactsDirectory)/osx-artifacts/GudPy-$VERSION $(System.ArtifactsDirectory)/osx-artifacts/GudPy-$VERSION $(System.ArtifactsDirectory)/windows-artifacts/GudPy-$VERSION.exe
    env:
      GITHUB_TOKEN: $(REPO_SECRET)
    displayName: 'Create Versioned Release (GitHub)'
