steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      specificBuildWithTriggering: true
      downloadType: 'single'
      artifactName: 'linux-artifacts'
    displayName: 'Download Linux Artifacts'
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      specificBuildWithTriggering: true
      downloadType: 'single'
      artifactName: 'osx-artifacts'
    displayName: 'Download OSX Artifacts'
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      specificBuildWithTriggering: true
      downloadType: 'single'
      artifactName: 'windows-artifacts'
    displayName: 'Download Windows Artifacts'
  - bash: |
      VERSION=$(grep "VERSION =" gudpy.spec | sed "s/.*\"\(.*\)\"/\1/g")
      git clone https://github.com/disorderedmaterials/scripts.git
      sed -i '' -e 's/trisyoungs/jswift-stfc/g' scripts/update-release
      sed -i '' -e 's/tristan.youngs/jared.swift/g' scripts/update-release
      ./scripts/update-release -r disorderedmaterials/gudpy -t ${VERSION} -n "${VERSION}" -f ReleaseNotes.md $(System.ArtifactsDirectory)/linux-artifacts/* $(System.ArtifactsDirectory)/windows-artifacts/*.exe $(System.ArtifactsDirectory)/windows-artifacts/*.zip $(System.ArtifactsDirectory)/osx-artifacts/*.app $(System.ArtifactsDirectory)/osx-artifacts/*.dmg
    env:
      GITHUB_TOKEN: $(REPO_SECRET)
    displayName: 'Create Versioned Release (GitHub)'
