steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.9"
      architecture: "x64"
    displayName: "Use Python 3.9"

  - script: |
      pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'
  - script: |
      pip install flake8
      python -m flake8 --exclude gudpy/core/isotopes.py --exclude gudpy/test/test_gud_file.py .
    condition: succeededOrFailed()
    displayName: "Static code analysis for PEP8 conformance using flake8. Ignore isotope definitions."    
  - script: python -m flake8 --exclude gudpy/core/isotopes.py --exclude gudpy/test/test_gud_file.py . > flake8.err.log
    displayName: "Capture flake8 error log"
    condition: failed()

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'flake8.err.log'
      ArtifactName: 'Flake8 Error log file'
    continueOnError: True
    condition: failed()