strategy:
  matrix:
    Python36:
      python.version: '3.6'
    Python38:
      python.version: '3.8'
  maxParallel: 2
steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: "x64"

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: "Install dependencies"
    
  - script: |
      pip install nose2
      nose2 --plugin nose2.plugins.junitxml --junit-xml tests
    displayName: 'Run tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '*.xml'
      failTaskOnFailedTests: true
      testRunTitle: 'GudPy on Python $(python.version) (ubuntu)'
    condition: succeededOrFailed()