trigger: none

pr:
  autoCancel: true
  branches:
    include:
      - "*"
  paths:
    exclude:
      - .azure-pipelines/continuous.yml

#Skip windows, for now.
# windowsPy36:
# {
#   pythonVersion: "3.6",
#   imageName: "windows-latest",
#   arch: "x86"      
# },
# windowsPy37:
# {
#   pythonVersion: "3.7",
#   imageName: "windows-latest",
#   arch: "x86"      
# },

variables:
  tag: 2021.test
  targets: >
    {
      linuxPy38:
      {
        pythonVersion: "3.8",
        imageName: "ubuntu-latest",
        arch: "x64",
        osName: "linux"
      },
      macOSPy38: 
      {
        pythonVersion: "3.8",
        imageName: "macOS-latest",
        arch: "x64",
        osName: "osx"
      }
    }
stages:

- stage: 'lint'
  displayName: Lint code
  jobs:
  - job: 'lint'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
        fetchDepth: 1
      - template: templates/lint.yml

- stage: 'test'
  displayName: 'Unit Tests'
  jobs:

    - job: 'test'
      strategy:
        matrix: $[ variables.targets ]
      displayName: 'Test'
      pool:
        vmImage: '$(imageName)'
      steps:
      - checkout: self
        fetchDepth: 1
      - template: templates/test.yml
        parameters:
          version: '$(pythonVersion)'
          arch: '$(arch)'
          os: '$(imageName)'
          osName: $(osName)
          tag: $(tag)

- stage: 'build'
  displayName: 'Build GudPy exe'
  jobs:

    - job: 'build'
      strategy:
        matrix: $[ variables.targets ]
      displayName: 'Build'
      pool:
        vmImage: '$(imageName)'
      steps:
        - checkout: self
          fetchDepth: 1
        - template: templates/build.yml
          parameters:
            version: '$(pythonVersion)'
            arch: '$(arch)'
            os: '$(imageName)'
            osName: $(osName)
            tag: $(tag)
