trigger:
  branches:
    include:
      - release/*

pr: none

variables:
  tag: 2021.1
  targets: >
    {
      linuxPy38:
      {
        pythonVersion: "3.8",
        imageName: "ubuntu-latest",
        arch: "x64",
        osName: "linux"
      },
      macOSPy38: 
      {
        pythonVersion: "3.8",
        imageName: "macOS-latest",
        arch: "x64",
        osName: "osx"
      },
      windowsPy38:
      {
        pythonVersion: "3.8",
        imageName: "windows-latest",
        arch: "x86",
        osName: "windows"      
      }
    }

stages:

- stage: 'lint'
  displayName: Lint code
  jobs:
  - job: 'lint'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
        fetchDepth: 1
      - template: templates/lint.yml

- stage: 'test'
  displayName: 'Unit Tests'
  jobs:

    - job: 'test'
      strategy:
        matrix: $[ variables.targets ]
      displayName: 'Test'
      pool:
        vmImage: '$(imageName)'
      steps:
      - checkout: self
        fetchDepth: 1
      - template: templates/test.yml
        parameters:
          version: '$(pythonVersion)'
          arch: '$(arch)'
          os: '$(imageName)'
          osName: $(osName)
          tag: $(tag)

- stage: 'build'
  displayName: 'Build GudPy exe'
  jobs:

    - job: 'build'
      strategy:
        matrix: $[ variables.targets ]
      displayName: 'Build'
      pool:
        vmImage: '$(imageName)'
      steps:
        - checkout: self
          fetchDepth: 1
        - template: templates/build.yml
          parameters:
            version: '$(pythonVersion)'
            arch: '$(arch)'
            os: '$(imageName)'
            osName: $(osName)
            tag: $(tag)
        - task: PublishBuildArtifacts@1
          inputs:
            PathToPublish: "dist/"
            ArtifactName: '$(osName)-artifacts'
          displayName: 'Publish $(osName) Artifacts'

- stage: 'release'
  displayName: 'Release'
  jobs:

    - job: 'release_github'
      displayName: 'Release'
      pool:
        vmImage: ubuntu-latest
      steps:
        - checkout: self
          fetchDepth: 1
        - template: templates/create_release.yml
