name: Pull Request

on:
  pull_request:
    branches:
    - '*'

env:
  pythonVersion: 3.9
  gudrunTag: 2022.4
  modexTag: 0.1.2

jobs:

  Lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Lint
      uses: "./.github/workflows/lint"
      with:
        pythonVersion: ${{ env.pythonVersion }}

