name: Release

on:
  push:
    branches:
    - 'release/*'
    - '*'

jobs:

  Lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup
      uses: "./.github/workflows/setup"
    - name: Lint
      uses: "./.github/workflows/lint"

  Test:
    needs: Lint
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup
      uses: "./.github/workflows/setup"
    - name: "Test (${{ matrix.os }})"
      uses: "./.github/workflows/test"

  BuildPackage:
    needs: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup
      uses: "./.github/workflows/setup"
    - name: "Build (${{ matrix.os }})"
      uses: "./.github/workflows/build"
    - name: "Package (${{ matrix.os }})"
      uses: "./.github/workflows/package"

  Publish:
    needs: BuildPackage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup
      uses: "./.github/workflows/setup"
    - name: "Publish"
      uses: "./.github/workflows/publish"
      with:
        isRelease: true
      env:
        HARBOR_USER: ${{ secrets.HARBOR_USER }}
        HARBOR_SECRET: ${{ secrets.HARBOR_SECRET }}
    - name: Update Version Information
      uses: "./.github/workflows/update-release-info"
      with:
        createPR: ${{ ! endsWith(github.ref, 'pre') }}
        releaseVersion: ${{ env.gudPyVersion }}

